using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DamosCSVParser {
	static class DamosNames {
		public const string _String = "String";
		public const string Name = "Name";
		public const string IdName = "IdName";
		public const string FolderName = "FolderName";
		public const string Type = "Type";
		public const string ViewMode = "ViewMode";
		public const string RWin = "RWin";
		public const string DataOrg = "DataOrg";
		public const string bReciprocal = "bReciprocal";
		public const string bSigned = "bSigned";
		public const string bDelta = "bDelta";
		public const string bPercent = "bPercent";
		public const string bOriginal = "bOriginal";
		public const string bOriginalValues = "bOriginalValues";
		public const string Columns = "Columns";
		public const string Rows = "Rows";
		public const string Radix = "Radix";
		public const string Comment = "Comment";
		public const string Precision = "Precision";
		public const string SkipBytes = "SkipBytes";
		public const string LineSkipBytes = "LineSkipBytes";
		public const string ValueRangeMin = "ValueRangeMin";
		public const string ValueRangeMax = "ValueRangeMax";
		public const string ValueRangeLock = "ValueRangeLock";
		public const string Marker = "Marker";
		public const string Fieldvalues_Name = "Fieldvalues.Name";
		public const string Fieldvalues_Unit = "Fieldvalues.Unit";
		public const string Fieldvalues_Factor = "Fieldvalues.Factor";
		public const string Fieldvalues_Offset = "Fieldvalues.Offset";
		public const string Fieldvalues_StartAddr_Cpu = "Fieldvalues.StartAddr.Cpu";
		public const string AxisX_Name = "AxisX.Name";
		public const string AxisX_IdName = "AxisX.IdName";
		public const string AxisX_Unit = "AxisX.Unit";
		public const string AxisX_Factor = "AxisX.Factor";
		public const string AxisX_Offset = "AxisX.Offset";
		public const string AxisX_Radix = "AxisX.Radix";
		public const string AxisX_bBackwards = "AxisX.bBackwards";
		public const string AxisX_bReciprocal = "AxisX.bReciprocal";
		public const string AxisX_bSigned = "AxisX.bSigned";
		public const string AxisX_Precision = "AxisX.Precision";
		public const string AxisX_DataSrc = "AxisX.DataSrc";
		public const string AxisX_DataHeader = "AxisX.DataHeader";
		public const string AxisX_DataAddr_Cpu = "AxisX.DataAddr.Cpu";
		public const string AxisX_DataOrg = "AxisX.DataOrg";
		public const string AxisX_SignatureByte = "AxisX.SignatureByte";
		public const string AxisX_SkipBytes = "AxisX.SkipBytes";
		public const string AxisY_Name = "AxisY.Name";
		public const string AxisY_IdName = "AxisY.IdName";
		public const string AxisY_Unit = "AxisY.Unit";
		public const string AxisY_Factor = "AxisY.Factor";
		public const string AxisY_Offset = "AxisY.Offset";
		public const string AxisY_Radix = "AxisY.Radix";
		public const string AxisY_bBackwards = "AxisY.bBackwards";
		public const string AxisY_bReciprocal = "AxisY.bReciprocal";
		public const string AxisY_bSigned = "AxisY.bSigned";
		public const string AxisY_Precision = "AxisY.Precision"; 
		public const string AxisY_DataSrc = "AxisY.DataSrc";
		public const string AxisY_DataHeader = "AxisY.DataHeader";
		public const string AxisY_DataAddr_Cpu = "AxisY.DataAddr.Cpu";
		public const string AxisY_DataOrg = "AxisY.DataOrg";
		public const string AxisY_SignatureByte = "AxisY.SignatureByte";
		public const string AxisY_SkipBytes = "AxisY.SkipBytes";
		public const string Fieldvalues_Values = "Fieldvalues.Values";
		public const string AxisX_Values = "AxisX.Values";
		public const string AxisY_Values = "AxisY.Values";
	}
}
